try:
  a = 345/10

except Exception as e:
  print(e)

else:   #gets executed when there is no error in try block 
  print("hey i am good")